version: '3'
# Nginx entrypoint
services:
  nginx:
    image: nginx:1.13
    links:
        - web
    ports:
        - "8000:80"
    # PHP-FPM service
  web:
      build:
        context: ~/sync/gi
        dockerfile: ./Dockerfile
      volumes:
     # put your link to the goal investor application on the left side of the colon
        - ~/sync/gi:/var/www/html
        - ./config/nginx-docker.conf:/etc/nginx/conf.d/default.conf
      links:
        - mysql:mysql
      working_dir: /var/www/html
      expose:
        - "9000"
    # MySQL Server
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_USER: drupal
        MYSQL_PASSWORD: drupal
        MYSQL_DATABASE: drupal
        MYSQL_ROOT_PASSWORD: 'drupal'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      expose:
        - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"
  redis:
    image: redis:3.2.10-alpine
